document.writeln("<style>");
document.writeln(".buybtc {");
document.writeln("    border: 1px solid #c6fbe7;");
document.writeln("    padding: 5px 10px 5px 10px;");
document.writeln("    margin: 10px 15px;");
document.writeln("    line-height: 50px;");
document.writeln("    border-radius: 3px;");
document.writeln("    box-shadow: 0 0 17px rgb(224 224 224 / 49%);");
document.writeln("    background: url(https://0xzx.com/img/coinzilla-fav.png) no-repeat #fff;");
document.writeln("    background-position: top 7px left 3px;");
document.writeln("}");
document.writeln(".buybtc:hover {");
document.writeln("    background: url(https://0xzx.com/img/coinzilla-fav.png) no-repeat #000;");
document.writeln("    background-position: top 7px left 3px;");
document.writeln("}");
document.writeln(".swap {");
document.writeln("    font-size: 18px;");
document.writeln("    font-weight: 700;");
document.writeln("    color: #757884;");
document.writeln("    padding-left: 25px;");
document.writeln("}");
document.writeln(".swapad {");
document.writeln("    text-shadow: none;");
document.writeln("    text-align: center;");
document.writeln("    max-width: 100%;");
document.writeln("    background: #ffffff;");
document.writeln("    border: 1px solid #eee;");
document.writeln("    box-shadow: 0 0 14px rgb(0 0 0 / 4%);");
document.writeln("}");
document.writeln("");
document.writeln(".swap:hover {");
document.writeln("    font-weight: 700;");
document.writeln("    color:#f75876;");
document.writeln("    font-style: italic;");
document.writeln("}");
document.writeln(".contract {");
document.writeln("    display: block;");
document.writeln("    width: 100%;");
document.writeln("    background: #e0f1ea;");
document.writeln("    font-size: 12px;");
document.writeln("    font-family: cursive;");
document.writeln("}");
document.writeln(".social {");
document.writeln("");
document.writeln("font-size: 12px;");
document.writeln(" font-family: cursive;");
document.writeln("}");
document.writeln(".contract-title {");
document.writeln("");
document.writeln("}");
document.writeln("a {");
document.writeln(" text-decoration: none!important;");
document.writeln("}");
document.writeln("hr {");
document.writeln("    background-color: rgb(243 243 243);");
document.writeln("    border: 0;");
document.writeln("    height: 1px;");
document.writeln("    margin: 1em 0;");
document.writeln("}");
document.writeln(".coinswap { border: 3px solid #26e269; padding: 5px 15px; background: #acfdcd; font-weight: 700; border-radius: 3px; box-shadow: 0px 0px 14px 0px #acdaba; }");
document.writeln(".coinswap:hover{border: 3px solid #6374ec;padding: 5px 15px;background: #c0d6f1;box-shadow: 0px 0px 14px 0px #b9e8e6;}");
document.writeln(".adcs {margin-bottom:15px}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'swapad\'>");
document.writeln("<img src=\'https://0xzx.com/img/cake.png\' style=\'height: 50px;float: left;line-height: 50px;\'><a href=\'https://exchange.pancakeswap.finance/#/swap?inputCurrency=0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b\' rel=\'nofollow external noopener noreferrer\' target=\'_blank\' ><span class=\'buybtc swap\'>SWAP 0XZX TOKEN</span></a>");
document.writeln("<div class=\'contract\'><a href=\'https://bscscan.com/token/0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b\' rel=\'nofollow external noopener noreferrer\' target=\'_blank\'>0x1fbb6ca220dcbe732f796fa9b13dd21cd654511b</a></div>");
document.writeln("<span class=\'social\'><a href=\'https://t.me/chat0x\' rel=\'nofollow external noopener noreferrer\' target=\'_blank\'>TELEGRAM: @chat0x</a></span> ~ <span class=\'social\'><a href=\'https://twitter.com/0xzxcom\' rel=\'nofollow external noopener noreferrer\' target=\'_blank\'>TWITTER: @0xzxcom</a></span>");
document.writeln("<hr>");
document.writeln("<div class=\'adcs\'>");
document.writeln("<a href=\'https://master.coinswap.space/farm?coinswapfriend=0xA007938E1Cd29B4CF94DF0F1BAFe64Eb7C356783\' rel=\'noreferrer nofollow external noopener\' target=\'_blank\'><span class=\'coinswap\'>Farm on CoinSwap</span></a></div>");
document.writeln("</div>");
